version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - /app/node_modules
      - ./:/app

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
    depends_on:
      - envoy
      - server
    volumes:
      - /app/ui/node_modules
      - ./ui:/app/ui
